-- KEYSTONE - Initial Database Schema
-- Version 1
-- Creates the complete application schema for a clean deployment.

-- =========================================================
-- CUSTOMERS
-- =========================================================

CREATE TABLE customers
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean,
    address varchar(255),
    company_name varchar(255) NOT NULL,
    customer_name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    phone_number varchar(255) NOT NULL,
    CONSTRAINT uk_customers_email UNIQUE (email)
);

-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK
    (
        role IN ('DISPATCHER', 'TECHNICIAN', 'MANAGER', 'CUSTOMER')
    )
);

-- =========================================================
-- SITES
-- =========================================================

CREATE TABLE sites
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(255),
    city varchar(255),
    country varchar(255),
    postal_code varchar(255),
    site_name varchar(255),
    state varchar(255),
    customer_id bigint NOT NULL,

    CONSTRAINT fk_sites_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
);

-- =========================================================
-- TECHNICIANS
-- =========================================================

CREATE TABLE technicians
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    email varchar(255) NOT NULL,
    phone_number varchar(255) NOT NULL,
    specialization varchar(255) NOT NULL,
    technician_name varchar(255) NOT NULL,

    CONSTRAINT uk_technicians_email UNIQUE (email)
);

-- =========================================================
-- PARTS
-- =========================================================

CREATE TABLE parts
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code varchar(255) NOT NULL,
    part_name varchar(255) NOT NULL,
    stock_quantity integer NOT NULL,
    unit_price double precision NOT NULL,

    CONSTRAINT uk_parts_code UNIQUE (part_code),
    CONSTRAINT parts_stock_quantity_check CHECK (stock_quantity >= 0),
    CONSTRAINT parts_unit_price_check CHECK (unit_price >= 0)
);

-- =========================================================
-- WORK ORDERS
-- =========================================================

CREATE TABLE work_orders
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(1000),
    priority varchar(255) NOT NULL,
    scheduled_date date NOT NULL,
    status varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    work_order_code varchar(255),

    customer_id bigint NOT NULL,
    site_id bigint NOT NULL,
    technician_id bigint,

    end_time timestamp(6),
    start_time timestamp(6),

    sla_breached boolean,
    sla_due_date timestamp(6),

    CONSTRAINT uk_work_orders_code UNIQUE (work_order_code),

    CONSTRAINT fk_work_orders_technician
        FOREIGN KEY (technician_id)
        REFERENCES technicians(id),

    CONSTRAINT fk_work_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id),

    CONSTRAINT fk_work_orders_site
        FOREIGN KEY (site_id)
        REFERENCES sites(id),

    CONSTRAINT work_orders_priority_check CHECK
    (
        priority IN ('LOW', 'MEDIUM', 'HIGH')
    ),

    CONSTRAINT work_orders_status_check CHECK
    (
        status IN
        (
            'NEW',
            'ASSIGNED',
            'IN_PROGRESS',
            'ON_HOLD',
            'COMPLETED',
            'CLOSED',
            'CANCELLED'
        )
    )
);

-- =========================================================
-- PART USAGE
-- =========================================================

CREATE TABLE part_usage
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity_used integer NOT NULL,
    part_id bigint NOT NULL,
    work_order_id bigint NOT NULL,

    CONSTRAINT fk_part_usage_part
        FOREIGN KEY (part_id)
        REFERENCES parts(id),

    CONSTRAINT fk_part_usage_work_order
        FOREIGN KEY (work_order_id)
        REFERENCES work_orders(id)
);

-- =========================================================
-- STATUS HISTORY
-- =========================================================

CREATE TABLE status_history
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at timestamp(6) NOT NULL,
    changed_by varchar(255) NOT NULL,
    new_status varchar(255) NOT NULL,
    old_status varchar(255) NOT NULL,
    work_order_id bigint NOT NULL,

    CONSTRAINT fk_status_history_work_order
        FOREIGN KEY (work_order_id)
        REFERENCES work_orders(id)
        ON DELETE CASCADE,

    CONSTRAINT status_history_new_status_check CHECK
    (
        new_status IN
        (
            'NEW',
            'ASSIGNED',
            'IN_PROGRESS',
            'ON_HOLD',
            'COMPLETED',
            'CLOSED',
            'CANCELLED'
        )
    ),

    CONSTRAINT status_history_old_status_check CHECK
    (
        old_status IN
        (
            'NEW',
            'ASSIGNED',
            'IN_PROGRESS',
            'ON_HOLD',
            'COMPLETED',
            'CLOSED',
            'CANCELLED'
        )
    )
);

-- =========================================================
-- TIME LOGS
-- =========================================================

CREATE TABLE time_logs
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    end_time timestamp(6) NOT NULL,
    hours_worked double precision NOT NULL,
    remarks varchar(500),
    start_time timestamp(6) NOT NULL,
    technician_id bigint NOT NULL,
    work_order_id bigint NOT NULL,

    CONSTRAINT fk_time_logs_work_order
        FOREIGN KEY (work_order_id)
        REFERENCES work_orders(id),

    CONSTRAINT fk_time_logs_technician
        FOREIGN KEY (technician_id)
        REFERENCES technicians(id)
);